# Generated by Django 4.2.5 on 2023-11-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
